[package]
name = "chapter06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono      = "0.4.23"  # chronoクレートの依存定義
chrono-tz   = "0.8.1"   # chrono-tzの依存定義