[package]
name = "chapter11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits  = "0.2.15"
thiserror   = "1.0.38"
anyhow      = "1.0.68"